repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude_types:
          - svg
    -   id: trailing-whitespace
        exclude_types:
          - svg
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: ^migrations/
        args:
          - --remove-all-unused-imports
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
